version: '3.3'

services:
  app1:
    build:
      context: .
      dockerfile: ./server/dockerfile.server
    ports:
      - "4070:4070"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  app2:
    build:
      context: .
      dockerfile: ./worker/dockerfile.worker
    ports:
      - "4080:4080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  app3:
    build:
      context: .
      dockerfile: ./client/dockerfile.client
    ports:
      - "5173:80"
    environment:
      - VITE_WEBSOCKET_URL="ws://0.0.0.0:4060"

    
  redis:
    image: "redis"
    ports:
      - "6379:6379"
